version: '3.8'
services:
  file-transfer-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        email: "${QT_EMAIL}"
        password: "${QT_PASS}"
    user: 0:0
    ports:
      - 8091:8091
      - "52000-52100:52000-52100"
    volumes:
      - /media:/media
